export {average} from './average';
export {ILinearLeastSquares} from './linear-least-squares';
export {linearLeastSquares} from './linear-least-squares';
export {median} from './median';
export {sum} from './sum';
export {variance} from './variance';
export {Interest} from './interest';
export {Line} from './line';
export {Point} from './point';
